### ISSUE TITLE
layer_factory.hpp:88] Check failed: registry.count(t ype) == 1 (0 vs. 1) Unknown layer type: ImageData (known types: )

### ISSUE THREAD

**Issue by jingleFun** [Microsoft/caffe#45]
Hi， I just want to use the libcaffe.lib in my project, but I encountered this problem, how can I solve it? Thank you

**Comment by sasagalic-MSFT** [comment]
Currently it is not possible to use libcaffe.lib outside Caffe solution due to collision between MS compiler and caffe internals. Without going into too much details only way to use libcaffe.lib would be to add new project to caffe.sln, link explicitly libcaffe.lib, add libcaffe as reference and make sure that "Use Library Dependency Inputs" property in reference settings is set to true.
For example refer to caffe project.
