### ISSUE TITLE
When compiled caffe .mexw64, using caffe .mexw64, there is memory problems.

### ISSUE THREAD

**Issue by Belinda-great** [Microsoft/caffe#95]
When i  compiled caffe .mexw64,in faster_rcnn, there is an error "Matlab has encountered an internal problem and needs to close" and closes matlab. Somebody had such error? Or it is better to address in technical support...

Thanks

**Comment by a980410** [comment]
I meet this problem too.
1.Your GPU memory may be too small.Faster rcnn require 3GB GPU memory at least.Otherwise,matlab will report error.
2;The caffe.mexw64 compiled form MS repo  does not have roi layer which is necessary in faster rcnn.You should compile Ren's caffe.If you use caffe and faster rcnn in windows like me,make sure the size of caffe_.mexw64 is 13MB.

**Comment by zer0n** [comment]
I just added ROI layer and Faster RCNN support to this. Please try it.
